export const ROUTES = {
  login: "Login",
  register: "Register",
  forgotPassword: "ForgotPassword",
  verifyAccount: "VerifyAccount",
  mainTabs: "MainTabs",
  profile: "Profile",
  tags: "Tags",
  verifyUpdate: "VerifyUpdate",
  resetPassword: "ResetPassword",
  dashboard: "Dashboard",
  transactions: "Transactions",
  transaction: "Transaction",
  insights: "Insights",
};
